### ISSUE TITLE
There is one extra error variable for all of rego files

### ISSUE THREAD

**Issue by shahinshirvani** [prancer-io/prancer-compliance-test#107]
There is one extra error variable for all of rego files
for example in below rego file:
https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/iac/activitylogalerts.rego
```
alerts_err = "Send me emails about alerts is set to OFF in Security Center" {
      azure_issue["alerts"]
}

alerts_miss_err = "Activitylog alerts attribute enabled missing in the resource" {
     azure_attribute_absence["alerts"]
}
      
```
we have two variables for calling the errors but in our master compliance files, we just call the first one
https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/iac/master-compliance-test.json

```
{
    "evals": [
        {
             "id": "PR-AZR-0090-ARM",
             "eval": "data.rule.alerts",
             "message": "data.rule.alerts_err",
             "remediationDescription" : ""
             "remediationFunction": ""
        }
    ]
}
```

In my opinion we can use same variable for both errors
for example:

```
alerts_err = "Send me emails about alerts is set to OFF in Security Center" {
      azure_issue["alerts"]
}

alerts_err = "Activitylog alerts attribute enabled missing in the resource" {
     azure_attribute_absence["alerts"]
}
      
```

**Comment by mr-maxo** [comment]
it was part of the initial request but if it is no longer needed we can remove it. What I would do is delete everything like `*_miss_err` and convert `{PROVIDER}_attribute_absence` to `{PROVIDER}_issue`...
