### ISSUE TITLE
for the Azure keyvault access policy, we should check for the existence of the `keys`, `secrets` and `certificates`

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#135]
https://github.com/prancer-io/prancer-compliance-test/blob/e3d9d530af26f06a338987be85eea29495d3cec2/azure/iac/KeyVaultvaults.rego#L11

`keys`, `secrets` and `certificates` are optional in the ARM template: 
https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?tabs=json

Other than the `count` test, we should also if they exist in the template.

**Comment by rezoan** [comment]
@farchide @shahinshirvani if we need to check if the azure keyvault is in use? keys and secrects should in a and condition and certificates should in a or condition. **if there is a key and secret generated or a certificate has been generated. we would be sure that the keyvault being in use.**

**Soln would be to implement a OR rule:**

```
azure_issue ["KeyVault"] {
    resource := input.resources[_]
    lower(resource.type) == "microsoft.keyvault/vaults"
    count(resource.properties.accessPolicies.permissions.keys) == 0
    count(resource.properties.accessPolicies.permissions.secrets) == 0
}

azure_issue ["KeyVault"] {
    resource := input.resources[_]
    lower(resource.type) == "microsoft.keyvault/vaults"
    count(resource.properties.accessPolicies.permissions.certificates) == 0
}
```

**Comment by farchide** [comment]
fixed in this PR:
https://github.com/prancer-io/prancer-compliance-test/pull/143
