### ISSUE TITLE
azurerm_key_vault_secret expiration is compared incorrectly.

### ISSUE THREAD

**Issue by rezoan** [prancer-io/prancer-compliance-test#141]
In **Azure->terraform->keyvaultsecrets.rego** `azurerm_key_vault_secret ` **expiration** is compared by `count(resource.properties.expiration_date) = 0` which is **clearly an assignment to 0**, 
this should be `count(resource.properties.expiration_date) == 0`

Also `count `function is only checking the **length of characters** in the variable `expiration_date` . other then `null ` if some one type `'abcd'` instead of valid date, this `count `will treat this as a valid date, **which is invalid** as well.

Ref file: [https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/terraform/keyvaultsecrets.rego](https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/terraform/keyvaultsecrets.rego)

**Comment by mr-maxo** [comment]
Missing `=` is definitely bug. `abcd` is not valid terraform value for `expiration_date`. I changed policy to check if the value starts with a date... PR is attached.
