### ISSUE TITLE
Azure AD RBAC integration for AKS cluster

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#145]
We need to have a new rule, to test for the AKS Azure AD enabled RBAC. this is different than the old RBAC rule we already have. the criteria should be based on the following parameters:

```
"aadProfileConfiguration": {
      "managed": "[parameters('aadProfileManaged')]",
      "enableAzureRBAC": "[parameters('aadProfileEnableAzureRBAC')]",
      "adminGroupObjectIDs": "[parameters('aadProfileAdminGroupObjectIDs')]",
      "tenantID": "[parameters('aadProfileTenantId')]"
}
```

https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.network/aks-application-gateway-ingress-controller/azuredeploy.json

**Comment by rezoan** [comment]
@farchide is it form terraform or iac or we need this for all?

**Comment by farchide** [comment]
@rezoan for both Azure ARM templates and Terraform

**Comment by rezoan** [comment]
Commits done so far:
- [aadProfile definition](https://github.com/prancer-io/prancer-armof/commit/33b265309e92f7b16134f84639380da0fdcfd7cc#diff-818571ccfe794a991c8e9da2719177886ab91bf27cd1533cc5e07b6181f78c9d)
- [aadProfile parameter definition](https://github.com/prancer-io/prancer-armof/commit/9fc0b2974396afbd544927e94a1fba31aa7eda82#diff-818571ccfe794a991c8e9da2719177886ab91bf27cd1533cc5e07b6181f78c9d)

**Comment by rezoan** [comment]
@farchide matching `managed `and `enableAzureRBAC` property should be enough right? or do you want me to match `adminGroupObjectIDs ` count as well?

**Comment by farchide** [comment]
@rezoan no need to check for `adminGroupObjectIDs`

**Comment by rezoan** [comment]
@farchide rules has been designed for ARM Templates:

Please verify below PRs
- https://github.com/prancer-io/prancer-compliance-test/pull/157
- https://github.com/prancer-io/prancer-armof/pull/193

**Will implement the same change to Terraform when there will be a new release available with terraform changes/updates for prancer.**

**Comment by rezoan** [comment]
**ToDo:** implement the same change to Terraform

**Comment by rezoan** [comment]
@farchide Added the rule for terraform.
