### ISSUE TITLE
AWS SSM Parameter "SecureString" is no logger supported

### ISSUE THREAD

**Issue by vatsalgit5118** [prancer-io/prancer-compliance-test#156]
[PR-AWS-0158-CFR](https://github.com/prancer-io/prancer-compliance-test/blob/master/aws/iac/ssm.rego#L6) : AWS SSM Parameter is not encrypted

As per the documentation, the "[SecureString](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html)" does not support for the property type.

**Comment by farchide** [comment]
@vatsalgit5118  / @harshilswan  what is the latest status on this?

**Comment by harshilswan** [comment]
@farchide, the property type `SecureString` of SSM is no longer supported by the AWS Cloudformation, that's why we have removed the rule.

**Comment by jaiminswan** [comment]
Already removed checked on the master
