### ISSUE TITLE
check the existence of a variable and value of that set to False on the rego file

### ISSUE THREAD

**Issue by shahinshirvani** [prancer-io/prancer-compliance-test#159]
We faced an issue when we want to check the existence of a variable and check the value of that has been false
for example on the following policy, at first, we want to check the existence of "enableNonSslPort" and after that, check the value of enableNonSslPort is "false"
https://gsl.dome9.com/D9.AZU.CRY.05.html

so for this arm template https://docs.microsoft.com/en-us/azure/templates/microsoft.cache/redis, when we want to check existence of enableNonSslPort, we used this condition normally :

```
azure_attribute_absence["enableNonSslPort"] {
    resource := input.resources[_]
    lower(resource.type) == "microsoft.cache/redis"
    resource.properties.enableNonSslPort
}
```

So according to rules of Open Policy Agent, in this case <resource.properties.enableNonSslPort> checkes
 
( resource.properties.enableNonSslPort exists ) and ( resource.properties.enableNonSslPort != False )
https://www.openpolicyagent.org/docs/latest/policy-reference/#objects
![rego](https://user-images.githubusercontent.com/76029421/126862890-368b6309-08c3-48be-9dce-d45e0f5aac68.png)

So the result of this test always failed and if we want to have a passed result, enableNonSslPort  must be exists and the value of that must be True and this is opposite of the policy

**Comment by rezoan** [comment]
@shahinshirvani so if `enableNonSslPort ` property does not exist, does the non ssl port (6379) get enabled by default ?
