### ISSUE TITLE
test `allowBlobPublicAccess` on storage account in Azure

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#160]
https://github.com/prancer-io/prancer-compliance-test/blob/2c05e0d1f377a90b770af0148d5a348b31db0a87/azure/iac/storageaccounts.rego#L1

We need to add a new test to check if `allowBlobPublicAccess` is disabled

if it is enabled or the property does not exist, we should fail the test:
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=json

We need the test for both IaC and Terraform

**Comment by rezoan** [comment]
**Added the new rule of IAC.
ToDo: Need to add this rule of Terraform.**

**Comment by rezoan** [comment]
@farchide terraform rule has been added.
