### ISSUE TITLE
Azure Databricks should not use Public IP and should be vnet integrated

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#174]
https://docs.microsoft.com/en-us/azure/templates/microsoft.databricks/workspaces?tabs=json

We should have policies for Azure Databricks, both the ARM template and Terraform

1. Azure Databricks should not use public IP address
2. Azure Databricks should have vnet integration

**Comment by rezoan** [comment]
Added the rules for ARM.
**ToDo: Need to add those for Terraform.**

@farchide do i need to add the `databricks `arm template to https://github.com/prancer-io/prancer-armof
