### ISSUE TITLE
regular expression on microsoft.security/securitycontacts are not matching multiple email address

### ISSUE THREAD

**Issue by rezoan** [prancer-io/prancer-compliance-test#175]
Please look into file https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/iac/securitycontacts.rego

the regular expression is currently matching only a single email address on `resource.properties.emails` but as per `SecurityContactProperties -> emails ` at https://docs.microsoft.com/en-us/azure/templates/microsoft.security/securitycontacts?tabs=json `emails `can have multiple email address though its not defined what will be the separator for this, assuming semicolon (;) but need to confirm by researching.

The regular expression need to match multiple email address.

**this can be handy for logic buildup (syntax may vary):** https://stackoverflow.com/questions/9809357/regex-for-validating-multiple-e-mail-addresses

**Comment by farchide** [comment]
@rezoan please take this one if you have time

**Comment by jaiminswan** [comment]
@rezoan Please look into it and close if already done

**Comment by rezoan** [comment]
Policy been updated as per latest API version 2020-01-01-preview. this issue is no longer valid. will closed when the linked PR get merged.
