### ISSUE TITLE
Azure SSE with CMK  for Azure Disk

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#325]
A new compliance test on the Azure IaC and Terraform to make sure Azure disks are encrypted with customer managed key.

Terraform template:
https://github.com/farchide/terraform-provider-azurerm/blob/main/examples/managed-disks/encrypted/main.tf

Microsoft help URL:
https://docs.microsoft.com/en-us/azure/virtual-machines/disks-enable-customer-managed-keys-portal

This test should be added to disks.rego file

**Comment by rezoan** [comment]
@farchide please take a look at https://msandbu.org/encryption-of-virtual-infrastructure-within-microsoft-azure/#:~:text=ADE%20can%20be%20used%20together,virtual%20machines%20encrypted%20using%20ADE.&text=You%20can%20back%20up%20and,VMs%20encrypted%20using%20standalone%20keys.
