### ISSUE TITLE
Azure keyvault enhanced policies development

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#336]
ARM template:
https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?tabs=json
Terraform template:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault

Guidance: When you deploy Key Vault resources, create or use an existing virtual network. Make sure that all Azure virtual networks follow an enterprise segmentation principle. It should align with the business risks. Isolate any system that could incur higher risk for the organization within its own virtual network. Secure the system sufficiently with either a network security group (NSG) or Azure Firewall.

Use Microsoft Defender for Cloud Adaptive Network Hardening to recommend NSG configurations that limit ports and source IPs based with the reference to external network traffic rules.

Based on your applications and enterprise segmentation strategy, restrict, or allow traffic between internal resources based on your NSG rules. For specific, well-defined applications like a three-tier app, this can be a highly secure deny-by-default.

Use Microsoft Sentinel to discover the use of legacy insecure protocols such as SSL/TLSv1, SMBv1, LM/NTLMv1, wDigest, Unsigned LDAP Binds, and weak ciphers in Kerberos.

Ingress Traffic from public internet: The Azure Key Vault will create a public IP that needs port 443 enabled on the public IP for ingress traffic.
https://docs.microsoft.com/en-us/security/benchmark/azure/baselines/key-vault-security-baseline

Policies:
1. disable the public network access to keyvault (defautlAction to be denied): https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Key%20Vault/AzureKeyVaultFirewallEnabled_Audit.json
2. if public access is enabled, protect keyvault with IP filter (IF private endpoint or service endpoint is enabled for keyvault, then even if the IP filter is empty we will pass this test)
3. bypass to AzureServices: https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?tabs=json#networkruleset
4. private endpoint should be enabled for Keyvault
5. Service Endpoint should be enabled for Keyvault: https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?tabs=json#virtualnetworkrule
6. Diagnostics settings should be enabled for Keyvault

**Comment by farchide** [comment]
The current Diagnostics settings for Keyvault does not work correctly:
https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/iac/diagnosticsettings.rego
since it is checking for the existence of the diagnostics settings regardless of the name of the keyvault.

with the correct test in place, this template should fail:
https://github.com/Azure/azure-quickstart-templates/blob/master/modules/Microsoft.KeyVault/vaults/1.0/azuredeploy.json

and this should pass:
https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.keyvault/key-vault-with-logging-create/azuredeploy.json

**Comment by farchide** [comment]
Private endpoint example:
https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.keyvault/key-vault-private-endpoint/azuredeploy.json

**Comment by farchide** [comment]
Service Endpoint for keyvault:
```
"networkAcls": {
      "bypass": "string",
      "defaultAction": "string",
      "ipRules": [
        {
          "value": "string"
        }
      ],
      "virtualNetworkRules": [
        {
          "id": "string",
          "ignoreMissingVnetServiceEndpoint": "bool"
        }
      ]
    
```
`networkAcls.virtualNetworkRules.id` should exist and have value

**Comment by farchide** [comment]
@rezoan 
for log diagnostics setting in terraform, we have to make sure `target_resource_id ` is equal to the keyvault:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting

The correct testcase for diagnostics settings is just checking for the existence of log.

**Comment by rezoan** [comment]
Azure TF are done.
