### ISSUE TITLE
Azure Redis enhanced policy development

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#341]
These policies should be added to our Azure ARM template and Terraform policies:
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/policy-reference

1. Azure Cache for Redis should disable public network access
2. Azure Cache for Redis should reside within a virtual network
3. Azure Cache for Redis should use private link

These policies can be tagged as "Best Practices" and title and descriptions can be copied from MS docs shared above

**Comment by rezoan** [comment]
Similar one: PR-AZR-TRF-SQL-066
