### ISSUE TITLE
Azure Storage account enhanced policies

### ISSUE THREAD

**Issue by farchide** [prancer-io/prancer-compliance-test#343]
These policies should be added to the storage account on Azure:
https://docs.microsoft.com/en-us/azure/storage/common/policy-reference

1. Configure Storage account to use a private link connection
2. Storage account encryption scopes should use customer-managed keys to encrypt data at rest
3. Storage account encryption scopes should use double encryption for data at rest
4. Storage accounts should have infrastructure encryption
5. Storage accounts should prevent shared key access
6. Storage Accounts should use a virtual network service endpoint
7. Storage accounts should use customer-managed key for encryption
8. Storage accounts should use private link

They can be tagged as Best practices and the title and descriptions can be get from MS docs

**Comment by farchide** [comment]
Configure diagnostic settings for storage accounts to Log Analytics workspace
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Storage/DataConnectorsStorageAccounts%20_PolicyAssignment.json

**Comment by rezoan** [comment]
01 & 08. Configure Storage account to use a private link connection -> PR-AZR-TRF-STR-019
02. Storage account encryption scopes should use customer-managed keys to encrypt data at rest -> PR-AZR-TRF-STR-008

**Comment by rezoan** [comment]
> Configure diagnostic settings for storage accounts to Log Analytics workspace https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Storage/DataConnectorsStorageAccounts%20_PolicyAssignment.json

PR-AZR-TRF-MNT-008
