### ISSUE TITLE
PR-AZR-TRF-VM-003 test case is getting skipped in angular web portal but template exist at https://github.com/prancer-io/prancer-terramerra/blob/master/azure/vm/main.tf

### ISSUE THREAD

**Issue by rezoan** [prancer-io/prancer-compliance-test#361]
PR-AZR-TRF-VM-003 test case is getting skipped in angular web portal but template exist at https://github.com/prancer-io/prancer-terramerra/blob/master/azure/vm/main.tf

**Comment by jaiminswan** [comment]
to be tested and reviewed

**Comment by rezoan** [comment]
PR-AZR-TRF-VM-003 is coming up fine in web portal. closing this issue.
