### ISSUE TITLE
PR-AZR-ARM-NET-004 and PR-AZR-ARM-NET-005 need to cover this template: https://github.com/prancer-io/prancer-infra/blob/master/provision/networks/VirtualNetworks.json

### ISSUE THREAD

**Issue by rezoan** [prancer-io/prancer-compliance-test#368]
@ajeybk found the issue mentioned in the subject line.
template in the subject line is getting skipped by PR-AZR-ARM-NET-004 and PR-AZR-ARM-NET-005.
@shahinshirvani We need to cover this template and update the rego rule.

**Comment by jaiminswan** [comment]
PR-AZR-ARM-NET-004 and PR-AZR-ARM-NET-005 are available in master-compliance-test file with their respective rego policies so closing it
